//USE TO ADD ITEMS TO ITEMSONVIEW ARRAY FOR VIEWING IN PRODUCT DETAILS PAGE
export const ADD_TO_DETAILS = "ADD_TO_DETAILS";

//USE TO ADD ITEMS TO THE CART ARRAY
export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";

//USE FOR DELETING ITEM FROM CART ARRAY
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";

//USE FOR CLEARING ALL ITEMS FROM THE CART ARRAY
export const CLEAR_ALL_ITEMS_FROM_CART = "CLEAR_ALL_ITEMS_FROM_CART";

//USE TO SHOW ALERT MESSAGE WHEN SEARCH ITEM IS NOT ADDED TO SEARCH PRODUCTS INPUT FIELD
export const SHOW_ALERT = "SHOW_ALERT";

//USE TO REMOVE ALERT AFTER DISPLAYING SHOW_ALERT MESSAGE TO NOTIFY USER TO ADD SOMETHING TO INPUT FIELD
export const REMOVE_ALERT = "REMOVE_ALERT";

//boolean to check if product is in cart
export const IF_IN_CART = "IF_IN_CART";
